-- Configuration Supabase Auth (Dashboard, pas SQL)
-- Authentication → URL Configuration
--   https://supabase.com/dashboard/project/uturszvczqxxqkdzehcj/auth/url-configuration
--
-- ⚠️ OBLIGATOIRE — Site URL (PAS localhost) :
--   https://compterendu.vercel.app
--
-- Redirect URLs (une par ligne) :
--   https://compterendu.vercel.app/**
--   http://localhost:5173/**
--
-- Si Site URL = localhost, les liens de confirmation renvoient vers localhost
-- même quand l'inscription se fait sur compterendu.vercel.app.
